// @novex/devtools postinstall v0.1.4
// Auto-scaffold non destructif pour Next.js (supporte app/ et src/app)
import fs from 'node:fs/promises';
import fss from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const J = (...xs) => path.join(ROOT, ...xs);
const ex = p => fss.existsSync(p);
const rd = p => fs.readFile(p, 'utf8');
const wr = (p, s) => fs.writeFile(p, s.endsWith('\n') ? s : s + '\n');
const mk = d => fs.mkdir(d, { recursive: true });
const now = () => new Date().toISOString().replace(/[:.]/g,'-');

const SRC_BASE = ex(J('src','app')) ? 'src' : '';
const APP = (...xs) => SRC_BASE ? J('src','app',...xs) : J('app',...xs);
const PAGES = (...xs) => SRC_BASE ? J('src','pages',...xs) : J('pages',...xs);

const hasTS = () =>
  ex(J('tsconfig.json')) || ex(APP('layout.tsx')) || ex(APP('page.tsx'));

async function ensureFile(fp, content) {
  if (ex(fp)) return false;
  await mk(path.dirname(fp));
  await wr(fp, content);
  return true;
}

async function injectThemeImport() {
  const cands = [APP('layout.tsx'), APP('layout.jsx'), PAGES('_app.tsx'), PAGES('_app.jsx')];
  for (const f of cands) {
    if (!ex(f)) continue;
    const src = await rd(f);
    if (src.includes('@novex/devtools/theme.css')) return { file:f, added:false };
    await wr(f, `import "@novex/devtools/theme.css";\n` + src);
    return { file:f, added:true };
  }
  return null;
}

function stripBadImports(src){
  return src
    .replace(/^\s*import\s*\{\s*DevTools\s*\}\s*from\s*['"]@novex\/devtools['"];\s*$/m, '')
    .replace(/^\s*import\s+['"]@novex\/devtools['"];\s*$/m, '');
}

const ROUTE_TS = `/* generated by @novex/devtools v0.1.4 */ 
import { NextRequest } from "next/server";
import { makeGet as ecGet,  makePost as ecPost  } from "@novex/devtools/adapters/next/export-code";
import { makeGet as edGet,  makePost as edPost  } from "@novex/devtools/adapters/next/export-docs";
import { makeGet as docGet, makePost as docPost } from "@novex/devtools/adapters/next/dev-docs";
import { makeGet as tcGet }                        from "@novex/devtools/adapters/next/technical-changelog";
import { makePost as scPost }                      from "@novex/devtools/adapters/next/summarize-changelog";
const getExportCode=ecGet(), postExportCode=ecPost();
const getExportDocs=edGet(), postExportDocs=edPost();
const getDoc=docGet(), postDoc=docPost();
const getTechChangelog=tcGet(), postSummarizeChangelog=scPost();
export async function GET(req: NextRequest, { params }: { params: { slug?: string[] } }) {
  const slug=params.slug??[];
  if(!slug.length) return new Response(JSON.stringify({
    ok:true,endpoints:["export-code","export-docs","[filename]","technical-changelog","summarize-changelog"]
  }),{headers:{"Content-Type":"application/json"}});
  const [first,...rest]=slug;
  if(first==="export-code") return getExportCode(req,{params:{} as any});
  if(first==="export-docs") return getExportDocs(req,{params:{} as any});
  if(first==="technical-changelog") return getTechChangelog(req,{params:{} as any});
  if(!rest.length) return getDoc(req,{params:{filename:first} as any});
  return new Response("Not found",{status:404});
}
export async function POST(req: NextRequest, { params }: { params: { slug?: string[] } }) {
  const slug=params.slug??[]; if(!slug.length) return new Response("Not found",{status:404});
  const [first,...rest]=slug;
  if(first==="export-code") return postExportCode(req,{params:{} as any});
  if(first==="export-docs") return postExportDocs(req,{params:{} as any});
  if(first==="summarize-changelog") return postSummarizeChangelog(req,{params:{} as any});
  if(!rest.length) return postDoc(req,{params:{filename:first} as any});
  return new Response("Not found",{status:404});
}
`;

const ROUTE_JS = `/* generated by @novex/devtools v0.1.4 */ 
import { makeGet as ecGet,  makePost as ecPost  } from "@novex/devtools/adapters/next/export-code";
import { makeGet as edGet,  makePost as edPost  } from "@novex/devtools/adapters/next/export-docs";
import { makeGet as docGet, makePost as docPost } from "@novex/devtools/adapters/next/dev-docs";
import { makeGet as tcGet }                        from "@novex/devtools/adapters/next/technical-changelog";
import { makePost as scPost }                      from "@novex/devtools/adapters/next/summarize-changelog";
const getExportCode=ecGet(), postExportCode=ecPost();
const getExportDocs=edGet(), postExportDocs=edPost();
const getDoc=docGet(), postDoc=docPost();
const getTechChangelog=tcGet(), postSummarizeChangelog=scPost();
export async function GET(req,{params}) {
  const slug=(params&&params.slug)||[];
  if(!slug.length) return new Response(JSON.stringify({
    ok:true,endpoints:["export-code","export-docs","[filename]","technical-changelog","summarize-changelog"]
  }),{headers:{"Content-Type":"application/json"}});
  const [first,...rest]=slug;
  if(first==="export-code") return getExportCode(req,{params:{}});
  if(first==="export-docs") return getExportDocs(req,{params:{}});
  if(first==="technical-changelog") return getTechChangelog(req,{params:{}});
  if(!rest.length) return getDoc(req,{params:{filename:first}});
  return new Response("Not found",{status:404});
}
export async function POST(req,{params}) {
  const slug=(params&&params.slug)||[];
  if(!slug.length) return new Response("Not found",{status:404});
  const [first,...rest]=slug;
  if(first==="export-code") return postExportCode(req,{params:{}});
  if(first==="export-docs") return postExportDocs(req,{params:{}});
  if(first==="summarize-changelog") return postSummarizeChangelog(req,{params:{}});
  if(!rest.length) return postDoc(req,{params:{filename:first}});
  return new Response("Not found",{status:404});
}
`;

const CARD_TSX = `"use client";
import { useState } from "react";
export default function DevtoolsCard(){
  const [status,setStatus]=useState("");
  const [docs,setDocs]=useState<string[]>([]);
  async function listDocs(){
    setStatus("Chargement docs…");
    const r=await fetch("/api/devtools/export-docs");
    if(!r.ok){ setStatus("DevTools OFF ou erreur"); return; }
    setDocs(await r.json()); setStatus("OK");
  }
  async function exportZip(){
    setStatus("Export ZIP…");
    const r=await fetch("/api/devtools/export-code",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({paths:["src"],mode:"zip"})});
    if(!r.ok){ setStatus("Erreur export"); return; }
    const b=await r.blob(); const url=URL.createObjectURL(b);
    const a=document.createElement("a"); a.href=url; a.download="code-export.zip"; a.click(); URL.revokeObjectURL(url);
    setStatus("ZIP téléchargé");
  }
  return (<section style={{marginTop:16}}>
    <div style={{padding:16,border:\"1px solid var(--border,#ddd)\",borderRadius:12}}>
      <h2 style={{marginTop:0}}>DevTools</h2>
      <p className="muted">ON/OFF via <code>docs/devtools.config.json</code></p>
      <div style={{display:\"flex\",gap:8,flexWrap:\"wrap\"}}>
        <button onClick={listDocs}>Lister docs</button>
        <button onClick={exportZip}>Exporter code (zip)</button>
      </div>
      <p>{status}</p>
      {docs.length>0 && <ul>{docs.map(d=><li key={d}>{d}</li>)}</ul>}
    </div>
  </section>);
}
`;

const CARD_JSX = `"use client";
import { useState } from "react";
export default function DevtoolsCard(){
  const [status,setStatus]=useState("");
  const [docs,setDocs]=useState([]);
  async function listDocs(){
    setStatus("Chargement docs…");
    const r=await fetch("/api/devtools/export-docs");
    if(!r.ok){ setStatus("DevTools OFF ou erreur"); return; }
    setDocs(await r.json()); setStatus("OK");
  }
  async function exportZip(){
    setStatus("Export ZIP…");
    const r=await fetch("/api/devtools/export-code",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({paths:["src"],mode:"zip"})});
    if(!r.ok){ setStatus("Erreur export"); return; }
    const b=await r.blob(); const url=URL.createObjectURL(b);
    const a=document.createElement("a"); a.href=url; a.download="code-export.zip"; a.click(); URL.revokeObjectURL(url);
    setStatus("ZIP téléchargé");
  }
  return (<section style={{marginTop:16}}>
    <div style={{padding:16,border:\"1px solid var(--border,#ddd)\",borderRadius:12}}>
      <h2 style={{marginTop:0}}>DevTools</h2>
      <p className="muted">ON/OFF via <code>docs/devtools.config.json</code></p>
      <div style={{display:\"flex\",gap:8,flexWrap:\"wrap\"}}>
        <button onClick={listDocs}>Lister docs</button>
        <button onClick={exportZip}>Exporter code (zip)</button>
      </div>
      <p>{status}</p>
      {docs.length>0 && <ul>{docs.map(d=><li key={d}>{d}</li>)}</ul>}
    </div>
  </section>);
}
`;

async function integrateIntoSettings(pagePath) {
  const backup = `${pagePath}.novex-backup-${now()}`;
  let src = await rd(pagePath);
  const orig = src;
  src = stripBadImports(src);
  if (!src.includes('_DevtoolsCard')) {
    src = `import DevtoolsCard from "./_DevtoolsCard";\n` + src;
  }
  if (src.includes('</main>')) {
    src = src.replace('</main>', '  <DevtoolsCard />\n</main>');
  } else if (src.includes('return (')) {
    src = src.replace(/return\s*\(\s*/, m => m + '\n  <DevtoolsCard />\n');
  } else {
    src += '\n<DevtoolsCard />\n';
  }
  if (src === orig) return { modified:false, backup:null };
  await wr(backup, orig);
  await wr(pagePath, src);
  return { modified:true, backup };
}

async function createSettings(isTS){
  const ext = isTS ? 'tsx' : 'jsx';
  const page = APP('settings','page.'+ext);
  const content = `export default function SettingsPage(){
  return (
    <main style={{padding:16}}>
      <h1>Settings</h1>
      <DevtoolsCard />
    </main>
  );
}
import DevtoolsCard from "./_DevtoolsCard";\n`;
  await mk(path.dirname(page)); await wr(page, content);
  return page;
}

async function main(){
  try{
    if (String(process.env.NOVEX_DEVTOOLS_NO_POSTINSTALL).toLowerCase()==='true') return;
    const isTS = hasTS();

    // 1) config
    const cfgCreated = await ensureFile(J('docs','devtools.config.json'), '{ "enabled": true }\n');

    // 2) route catch-all
    const routeDir = APP('api','devtools','[[...slug]]');
    await mk(routeDir);
    const routePath = APP('api','devtools','[[...slug]]', `route.${isTS ? 'ts' : 'js'}`);
    const routeCreated = await ensureFile(routePath, isTS ? ROUTE_TS : ROUTE_JS);

    // 3) theme import
    const theme = await injectThemeImport();

    // 4) card
    const cardPath = APP('settings','_DevtoolsCard.'+(isTS?'tsx':'jsx'));
    const cardCreated = await ensureFile(cardPath, isTS ? CARD_TSX : CARD_JSX);

    // 5) settings page integrate/create
    const candidates = [APP('settings','page.tsx'), APP('settings','page.jsx')];
    let settingsAction = null, settingsModified=false, settingsBackup=null;
    const existing = candidates.find(ex);
    if (existing) {
      const r = await integrateIntoSettings(existing);
      settingsAction = 'integrated'; settingsModified = r.modified; settingsBackup = r.backup;
    } else {
      await createSettings(isTS);
      settingsAction = 'created'; settingsModified = true;
    }

    console.log('[novex-devtools] postinstall report:', {
      base: SRC_BASE || '.',
      created: { config: cfgCreated, route: routeCreated, card: cardCreated },
      theme, settings: { action: settingsAction, modified: settingsModified, backup: settingsBackup }
    });
  }catch(e){
    console.warn('[novex-devtools] postinstall error (ignored):', e?.message || e);
  }
}
main();
